### ISSUE TITLE
The plugin does not work anymore since Git Extensions update to V4.2.1

### ISSUE THREAD

**Issue by Endymion78** [jasparfitt/GitExtensions.BranchNameCommitHintPlugin#1]
Since GitExtensions update to V4.2.1, an exception is thrown by the plugin when opening the commit dialog box in Bit Extensions :
"Method not found: 'System.String GitUIPluginInterfaces.IGitModule.GetSelectedBranch()'."
And the commit templates list isn't populated anymore.

Git Extensions version : 4.2.1.17611
Plugin version : 1.1.3

**Comment by ulrichb** [comment]
@Endymion78 Do you have a few minutes to check out the linked PR?

**Comment by Endymion78** [comment]
@ulrichb I can't give an opinion about how you fixed the issue, but I confirm that it solves the problem.
Thank you for your help.

**Comment by ulrichb** [comment]
@jasonparfitt Could you also have a look at the PR and if it's okay release a new version?

**Comment by jasparfitt** [comment]
yeah sorry about the delay, the PR looks like this works. I also had to pull in the latest version of GitUIPluginInterfaces.dll. I've merged up the PR and that's packaged in v 1.2.0

**Comment by ulrichb** [comment]
Many thanks! Just tested it successfully ❤️

**Comment by Endymion78** [comment]
I just got the update and confirm everything is okay.
Thanks to both of you !
